import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ra07z
 */
public class gui33 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gui33.class.getName());

    // 1. Deklarasi DefaultListModel
    DefaultListModel<String> dlm;

    /**
     * Creates new form gui33
     */
    public gui33() {
        initComponents();
        
        // 2. Inisialisasi model dan memasangnya ke jList1
        dlm = new DefaultListModel<>();
        jList1.setModel(dlm);
        
        // 3. Memperbaiki teks tombol agar sesuai dengan panduan Proyek 2
        jButton3.setText("insert data");
        jButton4.setText("add");
        jButton5.setText("update");
        jButton1.setText("delete");
        jButton2.setText("clear all");
        
        // 4. Menambahkan Action Listener manual untuk tombol yang belum memilikinya di kode awal
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Insert Data");

        jLabel1.setText("Item Name");

        jButton2.setText("Insert Data");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Insert Data");

        jButton4.setText("Insert Data");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Insert Data");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton2))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(183, Short.MAX_VALUE)
                    .addComponent(jButton3)
                    .addGap(129, 129, 129)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jButton3)
                    .addContainerGap(344, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    // --- LOGIKA TOMBOL PROYEK 2 ---

    // Aksi tombol CLEAR ALL
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        dlm.clear(); // Mengosongkan semua data [cite: 124]
    }                                        

    // Aksi tombol UPDATE
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int index = jList1.getSelectedIndex(); // Mengambil indeks yang dipilih [cite: 121]
        if (index != -1) { // Memastikan ada item yang dipilih
            String selected = jTextField1.getText(); // Mengambil teks baru [cite: 121]
            dlm.setElementAt(selected, index); // Mengganti item pada indeks tersebut [cite: 122]
            jTextField1.setText(""); // Mengosongkan textfield [cite: 123]
        }
    }                                        

    // Aksi tombol ADD
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (!jTextField1.getText().trim().isEmpty()) {
            dlm.addElement(jTextField1.getText()); // Menambahkan teks ke list [cite: 82]
            jTextField1.setText(""); // Mengosongkan textfield [cite: 83]
        }
    }                                        

    // Aksi tombol DELETE
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        int index = jList1.getSelectedIndex(); // Mengambil indeks yang dipilih [cite: 118]
        if (index != -1) { // Memastikan ada item yang dipilih
            dlm.removeElementAt(index); // Menghapus item berdasarkan indeks [cite: 118]
            jTextField1.setText(""); // Mengosongkan textfield [cite: 119]
        }
    }

    // Aksi tombol INSERT DATA
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // Data awal yang akan di-insert [cite: 125, 127]
        String[] items = {"buku", "meja", "kursi", "tas", "pintu"}; 
        
        for (String item : items) { // Loop untuk memasukkan setiap data [cite: 125]
            dlm.addElement(item); // Menambahkan data ke model [cite: 125]
        } // [cite: 126]
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new gui33().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}